import { StyleSheet } from 'react-native';

import { colors, fontFamilies, fontSizes, radius, spacing, tracking } from '@/theme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.darkest },
  container: {
    flex: 1,
    paddingHorizontal: spacing['3xl'],
    paddingTop: spacing['3xl'],
    paddingBottom: spacing['4xl'],
  },
  heading: {
    fontFamily: fontFamilies.oswaldBold,
    fontSize: fontSizes['2xl'],
    color: colors.textOnDark,
    textTransform: 'uppercase',
    letterSpacing: tracking.wide,
    marginBottom: spacing.base,
  },
  subheading: {
    fontFamily: fontFamilies.interRegular,
    fontSize: fontSizes.lg,
    color: colors.textLight,
    marginBottom: spacing['5xl'],
    lineHeight: 20,
  },
  bigButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.darker,
    borderColor: colors.borderGold,
    borderWidth: 1,
    borderRadius: radius['2xl'],
    paddingVertical: spacing['4xl'],
    paddingHorizontal: spacing['3xl'],
    marginBottom: spacing['2xl'],
    gap: spacing['2xl'],
  },
  bigButtonIcon: {
    width: 48,
    height: 48,
    borderRadius: radius.full,
    backgroundColor: colors.darkest,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bigButtonTextWrap: { flex: 1 },
  bigButtonTitle: {
    fontFamily: fontFamilies.oswaldBold,
    fontSize: fontSizes.xl,
    color: colors.textOnDark,
    textTransform: 'uppercase',
    letterSpacing: tracking.wide,
    marginBottom: spacing.xxs,
  },
  bigButtonSubtitle: {
    fontFamily: fontFamilies.interRegular,
    fontSize: fontSizes.md,
    color: colors.textLight,
  },
  bigButtonDisabled: {
    opacity: 0.5,
  },
  uploadingBox: {
    flex: 1,
    alignItems: 'stretch',
    justifyContent: 'center',
  },
  uploadingTitle: {
    fontFamily: fontFamilies.oswaldBold,
    fontSize: fontSizes['2xl'],
    color: colors.textOnDark,
    textTransform: 'uppercase',
    letterSpacing: tracking.wide,
    marginBottom: spacing.base,
    textAlign: 'center',
  },
  uploadingHint: {
    fontFamily: fontFamilies.interRegular,
    fontSize: fontSizes.md,
    color: colors.textLight,
    textAlign: 'center',
    marginBottom: spacing['4xl'],
  },
  errorBox: {
    flex: 1,
    alignItems: 'stretch',
    justifyContent: 'center',
    gap: spacing['2xl'],
  },
  errorTitle: {
    fontFamily: fontFamilies.oswaldBold,
    fontSize: fontSizes['2xl'],
    color: colors.danger,
    textTransform: 'uppercase',
    letterSpacing: tracking.wide,
    textAlign: 'center',
  },
  errorMessage: {
    fontFamily: fontFamilies.interRegular,
    fontSize: fontSizes.md,
    color: colors.textLight,
    textAlign: 'center',
    marginBottom: spacing['2xl'],
    lineHeight: 20,
  },
  primaryBtn: {
    backgroundColor: colors.gold,
    borderRadius: radius.xl,
    paddingVertical: spacing['3xl'],
    alignItems: 'center',
  },
  primaryBtnText: {
    fontFamily: fontFamilies.oswaldBold,
    fontSize: fontSizes.lg,
    color: colors.dark,
    textTransform: 'uppercase',
    letterSpacing: tracking.wide,
  },
  secondaryBtn: {
    borderColor: colors.gold,
    borderWidth: 1,
    borderRadius: radius.xl,
    paddingVertical: spacing['3xl'],
    alignItems: 'center',
  },
  secondaryBtnText: {
    fontFamily: fontFamilies.oswaldBold,
    fontSize: fontSizes.lg,
    color: colors.gold,
    textTransform: 'uppercase',
    letterSpacing: tracking.wide,
  },
});
